import { useEffect,useState } from 'react';
import { ethers } from "ethers";

import Head from 'next/head'

import MarketContractABI from '../abi/contracts/Market.sol/Market.json';
import AccountContractABI from '../abi/contracts/Account.sol/Account.json';
import OrderContractABI from '../abi/contracts/Order.sol/Order.json';

import addresses from '../address.json';
import Announcement from '../components/Announcement.js';


export default function Home() {
  const [orders,setOrders] = useState([])
  useEffect(() => { initialMarket() },[])

  async function initialMarket(){
    const provider = new ethers.providers.Web3Provider(window.ethereum)
    await provider.send("eth_requestAccounts", []);

    const signer = provider.getSigner()

    const marketContract = new ethers.Contract(addresses['marketContract'], MarketContractABI, provider);
    const accountLength = await marketContract.getAccountLength()

    let _orders = []

    for (let i = 0; i < accountLength; i++) {
      let accountAddress = await marketContract.accountKeys(i)
      let accountContractAddress = await marketContract.accounts(accountAddress)
      let accountContract = new ethers.Contract(accountContractAddress, AccountContractABI, provider);

      let accountOrderLength = (await accountContract.getOrderLength()).toNumber()

      for (let x = 1; x <= accountOrderLength; x++) {
        let orderAddress = await accountContract.orders(x);
        let orderContract = new ethers.Contract(orderAddress, OrderContractABI, provider);

        let orderName = await orderContract.name();
        let orderDesc = await orderContract.desc();
        let orderPrice = await orderContract.price();
        let orderImgs = await orderContract.imgUrl(0);

        _orders.push({
          name: orderName,
          desc: orderDesc,
          price: orderPrice,
          img: orderImgs,
        })
      }
    }

    if(_orders.length != 0){
      console.log(_orders)
      setOrders(_orders)
    }

  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Announcement />

      <div class="grid grid-cols-3 gap-4 py-5 px-32">
        { orders.map((p) => (
          <a class="block p-12 shadow-lg" href="/product/limited-edition-sports-trainer">
            <div class="flex justify-center">
              <strong class="relative h-6 px-4 text-xs leading-6 text-white uppercase bg-black">
                New
              </strong>
            </div>

            <img
              alt="Product Image"
              src={p.img}
              class="object-fit w-full -mt-3 h-[300px] sm:h-[350px]"
            />

            <h5 class="mt-4 text-sm text-gray-700">{p.name}</h5>

            <div class="flex items-center justify-between mt-4 font-medium">
              <p>ETHER {p.price.toNumber()}</p>
              <a href="" class="btn btn-wide">Buy</a>
            </div>
          </a>
      )) }
      </div>



    </div>
  )
}
